# Generated by Django 4.2.6 on 2023-10-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название игры')),
                ('description', models.TextField(verbose_name='Укажите описание игры')),
                ('image', models.ImageField(upload_to='game/', verbose_name='Загрузите фото')),
                ('cost', models.PositiveIntegerField(verbose_name='Укажите цену')),
                ('year', models.DateField(null=True, verbose_name='Укажите дату выпуска игры')),
                ('publisher', models.CharField(max_length=100, verbose_name='Укажите издателя игры')),
                ('genre', models.CharField(choices=[('MMORPG', 'MMORPG'), ('Shooter', 'Shooter'), ('Strategy', 'Strategy'), ('Horror', 'Horror')], max_length=100, verbose_name='Укажите жанр')),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PS', 'PS'), ('Xbox', 'Xbox')], max_length=100, verbose_name='Укажите платформу')),
                ('trailer', models.URLField(blank=True, verbose_name='Укажите трейлер')),
                ('gameplay', models.URLField(blank=True, verbose_name='Укажите видео с геймплеем')),
            ],
        ),
    ]
